version: '3.8'

services:
  # --- SERVIÇO DO BANCO DE DADOS (MySQL) ---
  db_mysql:
    image: mysql:8.0
    container_name: mysql_smartlock
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root # Senha do banco
      MYSQL_DATABASE: smartlock_db # Nome do banco que o Django vai usar
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  # --- SERVIÇO DO BROKER MQTT (EMQX) ---
  emqx_broker:
    image: emqx/emqx:latest
    container_name: emqx_smartlock
    restart: always
    ports:
      - "1883:1883"      # Porta do protocolo MQTT (usada pelo NodeMCU e Python)
      - "18083:18083"    # Painel de Controle Dashbord (Acesse no navegador)
      - "8083:8083"      # WebSocket
      - "8084:8084"      # WebSocket Seguro
    volumes:
      - emqx_data:/opt/emqx/data
      - emqx_log:/opt/emqx/log

volumes:
  mysql_data:
  emqx_data:
  emqx_log: